dist: xenial
services:
  - docker

before_install:
  - docker build -t gutku10/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gutku10/docker-react npm run test

# deploy:
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "docker-react"
#     env: "DockerReact-env"
#     bucket_name: "elasticbeanstalk-us-east-2-799795951143"
#     bucket_path: "docker-react"
#     on:
#         branch: master
    
#     ACCESS_KEY_ID: $AWS_ACCESS_KEY
#     secret_access_key:
#         secure: "$AWS_SECRET_KEY"