version: '3'
services:
    web:
        stdin_open: true
        tty: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        
        volumes: 
            - /app/node_modules
            - . :/app


